Learning from TA4H
Azure-Samples/azure-ml-federated-learning pull request #11
Opened 2022-04-09 00:36 UTC by jialei777

Updates:
- change the k8s version
- add the script to change the computer instance size

2022-04-10 00:52 UTC, talbaumel approved these changes

2022-04-11 20:57 UTC, dkmiller requested changes

2022-04-11 20:57 UTC, dkmiller commented on automated_provisioning/kube_instance/my_instance_type.yaml
> +      memory: "128Gi"
Can you add a link / guidelines on what these values mean and how to choose them?

2022-04-11 20:57 UTC, dkmiller commented on automated_provisioning/README.md
> +az account set --subscription "subscription-of-Cluster"
Rather than adding manual docs, can you add a PowerShell script which applies this logic?

2022-04-11 20:57 UTC, dkmiller commented on automated_provisioning/README.md
> +To verify, go to the orchestrator AML workspace, and find the attached cluster by click "Compute" -> "Attached computers" and search your cluster with "AML-Compute-Name".
Suggest using `&mapsto;`, which will render as &mapsto;

2022-04-15 16:38 UTC, dkmiller approved these changes
Thanks for the quick turnaround!

2022-04-15 16:44 UTC, merged