Provide fixes and unified approach for measuring time across communication techniques in VFL
Azure-Samples/azure-ml-federated-learning pull request #304
Opened 2023-03-20 15:50 UTC by majercakdavid

## Purpose
More precise and fine grained metrics for communication

## What is the expected review turnaround time?

Urgency:
- [ ] High (needs review today)
- [X] Medium (needs review within a few days - most common)
- [ ] Low (can wait a week)

## Does this introduce a breaking change?

```
[ ] Yes
[X] No
```

## Pull Request Type
What kind of change does this Pull Request introduce?

```
[ ] Bugfix
[X] Feature
[ ] Code style update (formatting, local variables)
[ ] Refactoring (no functional changes, no api changes)
[ ] Documentation content changes
[ ] Other... Please describe:
```

2023-03-20 16:24 UTC, jfomhover commented on examples/components/CCFRAUD_VERTICAL/traininsilo/aml_comm.py
> +        assert destination != self._rank
can you just add some error message here to explain why that's happening? (it won't, but just in case)

2023-03-20 16:25 UTC, jfomhover commented on examples/components/CCFRAUD_VERTICAL/traininsilo/aml_comm.py
> +        assert source != self._rank
same comment here

2023-03-20 16:27 UTC, jfomhover reviewed
A couple of minor changes needed, but otherwise looks good

2023-03-20 16:45 UTC, thomasp-ms approved these changes
Looks good overall. 
- There are a couple of magic numbers in these files (3, 1024) but they were not introduced in this PR so don't block on that.
- Would it be worth counting the retries as well? (For instance, if the sending times get much higher all of a sudden, is it just because of network latency, or is it because there are direct failures?)

2023-03-20 20:32 UTC, jfomhover submitted a review, later dismissed

2023-03-20 20:41 UTC, thomasp-ms commented on examples/components/CCFRAUD_VERTICAL/traininsilo/aml_comm.py
> +                self._stats["send_retries"] += 1
Shouldn't this be `send_retries_cnt`? (here and througout, also for recv, also in other file)

2023-03-21 03:10 UTC, jfomhover approved these changes

2023-03-21 15:40 UTC, thomasp-ms requested changes
There is still a mismatch with `recv_retries_cnt`

2023-03-21 16:02 UTC, merged